//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MISA.AMIS.Api.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceApi {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceApi() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MISA.AMIS.Api.Resources.ResourceApi", typeof(ResourceApi).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DepartmentCode không được phép null.
        /// </summary>
        public static string Dev_ErrorMsg__Null_DepartmentCode {
            get {
                return ResourceManager.GetString("Dev_ErrorMsg__Null_DepartmentCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EmployeeCode không được phép null.
        /// </summary>
        public static string Dev_ErrorMsg__Null_EmployeeCode {
            get {
                return ResourceManager.GetString("Dev_ErrorMsg__Null_EmployeeCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PositionCode không được phép null.
        /// </summary>
        public static string Dev_ErrorMsg__Null_PositionCode {
            get {
                return ResourceManager.GetString("Dev_ErrorMsg__Null_PositionCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trùng EmployeeCode.
        /// </summary>
        public static string Dev_ErrorMsg_Check_EmployeeCode {
            get {
                return ResourceManager.GetString("Dev_ErrorMsg_Check_EmployeeCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email không đúng định dạng.
        /// </summary>
        public static string Dev_ErrorMsg_FormatEmail {
            get {
                return ResourceManager.GetString("Dev_ErrorMsg_FormatEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email không được phép null.
        /// </summary>
        public static string Dev_ErrorMsg_Null_Email {
            get {
                return ResourceManager.GetString("Dev_ErrorMsg_Null_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FullName không được phép null.
        /// </summary>
        public static string Dev_ErrorMsg_Null_FullName {
            get {
                return ResourceManager.GetString("Dev_ErrorMsg_Null_FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IdentityNumber không được phép null.
        /// </summary>
        public static string Dev_ErrorMsg_Null_IdentityNumber {
            get {
                return ResourceManager.GetString("Dev_ErrorMsg_Null_IdentityNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PhoneNumber không được phép null.
        /// </summary>
        public static string Dev_ErrorMsg_Null_PhoneNumber {
            get {
                return ResourceManager.GetString("Dev_ErrorMsg_Null_PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EmployeeId is not valid.
        /// </summary>
        public static string Dev_NotValid_IdEmployee {
            get {
                return ResourceManager.GetString("Dev_NotValid_IdEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có lỗi xảy ra, vui lòng liên hệ cho MISA.
        /// </summary>
        public static string Exception_ErrorMsg {
            get {
                return ResourceManager.GetString("Exception_ErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID nhân viên không tồn tại.
        /// </summary>
        public static string NotValid_IdEmployee {
            get {
                return ResourceManager.GetString("NotValid_IdEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã nhân viên đã tồn tại.
        /// </summary>
        public static string User_ErrorMsg_Check_EmployeeCode {
            get {
                return ResourceManager.GetString("User_ErrorMsg_Check_EmployeeCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email không đúng định dạng.
        /// </summary>
        public static string User_ErrorMsg_FormatEmail {
            get {
                return ResourceManager.GetString("User_ErrorMsg_FormatEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không có dữ liệu.
        /// </summary>
        public static string User_ErrorMsg_NoContent {
            get {
                return ResourceManager.GetString("User_ErrorMsg_NoContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã phòng ban không được phép để trống.
        /// </summary>
        public static string User_ErrorMsg_Null_DepartmentCode {
            get {
                return ResourceManager.GetString("User_ErrorMsg_Null_DepartmentCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email không được phép để trống.
        /// </summary>
        public static string User_ErrorMsg_Null_Email {
            get {
                return ResourceManager.GetString("User_ErrorMsg_Null_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã nhân viên không được phép để trống.
        /// </summary>
        public static string User_ErrorMsg_Null_EmployeeCode {
            get {
                return ResourceManager.GetString("User_ErrorMsg_Null_EmployeeCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Họ và tên nhân viên không được phép để trống.
        /// </summary>
        public static string User_ErrorMsg_Null_FullName {
            get {
                return ResourceManager.GetString("User_ErrorMsg_Null_FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số CMTND/Căn cước không được phép để trống.
        /// </summary>
        public static string User_ErrorMsg_Null_IdentityNumber {
            get {
                return ResourceManager.GetString("User_ErrorMsg_Null_IdentityNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số điện thoại không được phép để trống.
        /// </summary>
        public static string User_ErrorMsg_Null_PhoneNumber {
            get {
                return ResourceManager.GetString("User_ErrorMsg_Null_PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã vị trí không được phép để trống.
        /// </summary>
        public static string User_ErrorMsg_Null_PositionCode {
            get {
                return ResourceManager.GetString("User_ErrorMsg_Null_PositionCode", resourceCulture);
            }
        }
    }
}
